---
title: "Chapter_5_Challenge_BlackBoxModels"
author: "LukasMackel"
date: "2024-06-24"
output: html_document
---

Explaining Black Box Models with LIME


```{r}
# LIME FEATURE EXPLANATION ----

# 1. Setup ----

# Load Libraries 

library(h2o)
library(recipes)
library(readxl)
library(tidyverse)
library(tidyquant)
library(lime)

# Load Data
employee_attrition_tbl <- read_csv("datasets-1067-1925-WA_Fn-UseC_-HR-Employee-Attrition.csv")
definitions_raw_tbl    <- read_excel("data_definitions.xlsx", sheet = 1, col_names = FALSE)
```
```{r}
process_hr_data_readable <- function(data, definitions_tbl) {
  
  definitions_list <- definitions_tbl %>%
    fill(...1, .direction = "down") %>%
    filter(!is.na(...2)) %>%
    separate(...2, into = c("key", "value"), sep = " '", remove = TRUE) %>%
    rename(column_name = ...1) %>%
    mutate(key = as.numeric(key)) %>%
    mutate(value = value %>% str_replace(pattern = "'", replacement = "")) %>%
    split(.$column_name) %>%
    map(~ select(., -column_name)) %>%
    map(~ mutate(., value = as_factor(value))) 
  
  for (i in seq_along(definitions_list)) {
    list_name <- names(definitions_list)[i]
    colnames(definitions_list[[i]]) <- c(list_name, paste0(list_name, "_value"))
  }
  
  data_merged_tbl <- list(HR_Data = data) %>%
    append(definitions_list, after = 1) %>%
    reduce(left_join) %>%
    select(-one_of(names(definitions_list))) %>%
    set_names(str_replace_all(names(.), pattern = "_value", 
                              replacement = "")) %>%
    select(sort(names(.))) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(
      BusinessTravel = BusinessTravel %>% fct_relevel("Non-Travel", 
                                                      "Travel_Rarely", 
                                                      "Travel_Frequently"),
      MaritalStatus  = MaritalStatus %>% fct_relevel("Single", 
                                                     "Married", 
                                                     "Divorced")
    )
  
  return(data_merged_tbl)
  
}

employee_attrition_readable_tbl <- process_hr_data_readable(employee_attrition_tbl, definitions_raw_tbl)
```
```{r}
# Split into test and train
set.seed(seed = 1113)
split_obj <- rsample::initial_split(employee_attrition_readable_tbl, prop = 0.85)

# Assign training and test data
train_readable_tbl <- training(split_obj)
test_readable_tbl  <- testing(split_obj)

# ML Preprocessing Recipe 
recipe_obj <- recipe(Attrition ~ ., data = train_readable_tbl) %>%
                step_zv(all_predictors()) %>%
                step_mutate_at(c("JobLevel", "StockOptionLevel"), fn = as.factor) %>% 
                prep()

recipe_obj
```
```{r}
train_tbl <- bake(recipe_obj, new_data = train_readable_tbl)
test_tbl  <- bake(recipe_obj, new_data = test_readable_tbl)

# 2. Models ----

h2o.init()
```
```{r}
automl_leader <- h2o.loadModel("04_Modeling/h20_models/DRF_1_AutoML_28_20230520_183822")
automl_leader
```
```{r}
# 3. LIME ----

# 3.1 Making Predictions ----

predictions_tbl <- automl_leader %>% 
    h2o.predict(newdata = as.h2o(test_tbl)) %>%
    as.tibble() %>%
    bind_cols(
        test_tbl %>%
            select(Attrition, EmployeeNumber)
    )
```

```{r}
predictions_tbl

# 3.2 Single Explanation ----

explainer <- train_tbl %>%
    select(-Attrition) %>%
    lime(
        model           = automl_leader,
        bin_continuous  = TRUE,
        n_bins          = 4,
        quantile_bins   = TRUE
    )

explainer
```
```{r}
explanation <- test_tbl %>%
    slice(1) %>%
    select(-Attrition) %>%
    lime::explain(
    
        # Pass our explainer object
        explainer = explainer,
        # Because it is a binary classification model: 1
        n_labels   = 1,
        # number of features to be returned
        n_features = 8,
        # number of localized linear models
        n_permutations = 5000,
        # Let's start with 1
        kernel_width   = 1
    )
explanation
```
```{r}
explanation %>%
    as.tibble() %>%
    select(feature:prediction) 
```

```{r}
g <- plot_features(explanation = explanation, ncol = 1)

# 3.3 Multiple Explanations ----

explanation <- test_tbl %>%
    slice(1:20) %>%
    select(-Attrition) %>%
    lime::explain(
        explainer = explainer,
        n_labels   = 1,
        n_features = 8,
        n_permutations = 5000,
        kernel_width   = 0.5
    )
explanation %>%
    as.tibble()

plot_features(explanation, ncol = 4)

plot_explanations(explanation)
```
-------------------------------

The above part was again from the lecture material

Now comes my solution for the challenge:


Part 1:
```


```{r}

library(ggplot2)

explanation %>% as.tibble()
# Reference
explanation %>% filter(case == 1) %>% plot_features()
```
```


```{r}

explanation %>%
    filter(case == 1) %>%
    ggplot(aes(x = fct_reorder(feature,abs(feature_weight)),y = feature_weight,fill = feature_weight < 0)) +
    coord_flip() +
    geom_col(just = 0.5) + 
    labs( title = paste0(
      "Case: ","1","\n",
      "Label: ",filter(explanation,case == 1)[1,]$label,"\n",
      "Probability: ",filter(explanation,case == 1)[1,]$label_prob%>%round(2),"\n",
      "Explanation Fit: ",filter(explanation,case == 1)[1,]$model_r2%>%round(2),"\n"
      ),
      x = "Feature",
      y = "Weight",
      fill = ""
    ) +
    scale_x_discrete(labels=explanation %>% filter(case == 1) %>% arrange(abs(feature_weight)) %>% .$feature_desc) +
    theme(legend.position = "bottom",
          panel.background = element_blank(),
          panel.grid.major.x = element_line(color="#EBEBEB"),
          panel.grid.minor.x = element_line(color="#EBEBEB")
    ) +
    scale_fill_manual(values=c("#4682B4", "#B22222"),labels=c("Supports","Contradics"))
```

Part 2:

```{r}

plot_explanations(explanation)

explanation %>%
    ggplot(aes(x = case,y = fct_reorder(feature,abs(label_prob)),fill = feature_weight)) +
    facet_wrap(~label) + 
    geom_tile() + 
  # axis description
    labs(
      x = "CaseNumber",
      y = "Feature"
    ) +
    scale_y_discrete(labels=explanation%>% arrange(abs(label_prob)) %>% .$feature_desc) +
    theme(panel.background = element_blank(),
          panel.grid = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
    ) +
  scale_fill_gradient2('Feature \n weight', low = '#B9362F', mid = "white", high = '#4B85B6') # legend

```


